version: '2'
services:
  osiris-virtualsensornet-database:
    container_name: osiris-virtualsensornet-database-container
    image: postgres
    ports:
    - "5433:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=virtualsensornet
    volumes:
    - ./volume:/var/lib/postgresql/data
    depends_on:
    - osiris-communication-layer
