version: '2'
services:
  osiris-min-function:
    container_name: osiris-min-function-container
    build: .
    ports:
    - "8087:8087"
    links:
    - osiris-communication-layer
    environment:
    - JAR_VERSION=1.0.0
    - RABBITMQ_IP=localhost
    - RABBITMQ_USERNAME=guest
    - RABBITMQ_PASSWORD=guest
    depends_on:
    - osiris-communication-layer
    - osiris-sensornet-database
    - osiris-sensornet-omcp
    - osiris-virtualsensornet-database
    - osiris-virtualsensornet-omcp
